# Generated by Django 5.1 on 2024-08-31 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountModel',
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile Number Must contain 10 digits', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain chars...', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
