# Generated by Django 5.1 on 2024-08-31 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_delete_accountmodel_alter_customermodel_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accno', models.BigIntegerField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('account_type', models.CharField(max_length=100)),
                ('account_owner', models.CharField(max_length=100)),
                ('account_status', models.BooleanField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.customermodel')),
            ],
        ),
    ]
