# Generated by Django 5.1 on 2024-08-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_accountmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='account_status',
            field=models.BooleanField(default=False),
        ),
    ]
