# Generated by Django 5.1 on 2024-09-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_alter_accountmodel_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatmentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opration', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
