# Generated by Django 5.1 on 2024-09-01 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_statmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='statmentmodel',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountapp.accountmodel'),
            preserve_default=False,
        ),
    ]
